const KEY='freelance_tracker_v2';
const seed={tasks:[],subscriptions:[],goals:[],money:[],revenue:[]};
function data(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null')||seed;for(const k in seed)d[k]??=[];cleanup(d);save(d);return d}catch{return structuredClone(seed)}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))} function id(p){return p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,7)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function iso(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function date(v){if(!v)return null;const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)} function fmtDate(v){return date(v)?.toLocaleDateString('en-ZA',{day:'numeric',month:'short',year:'numeric'})||'—'}
function money(n,c){if(c==='ZAR')return 'R'+Number(n).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2});if(c==='USD')return '$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});return Math.round(Number(n)).toLocaleString()+' Robux'}
function daysLeft(v){const d=date(v);if(!d)return['No deadline',''];d.setHours(0,0,0,0);const t=new Date();t.setHours(0,0,0,0);const n=Math.round((d-t)/86400000);if(n<0)return[Math.abs(n)+' day'+(Math.abs(n)==1?'':'s')+' overdue','overdue'];if(n===0)return['Today','today'];return[n+' day'+(n===1?'':'s')+' left','']}
function cleanup(d){const cut=Date.now()-172800000;for(const k of ['tasks','goals'])d[k]=d[k].filter(x=>!x.completedAt||new Date(x.completedAt).getTime()>cut)}
function open(id){document.getElementById(id)?.classList.remove('hidden')}function close(){document.querySelectorAll('.modal-backdrop').forEach(x=>x.classList.add('hidden'))}
document.addEventListener('click',e=>{const o=e.target.closest('[data-open-modal]');if(o)open(o.dataset.openModal);if(e.target.matches('[data-close-modal]')||e.target.classList.contains('modal-backdrop'))close()});document.addEventListener('keydown',e=>e.key==='Escape'&&close());

function taskCard(t){const p=String(t.pay).trim()==='?'?'UNKNOWN':esc(t.pay);const dl=daysLeft(t.deadline);return `<article class="item-card ${t.completedAt?'completed':''}"><div class="item-top"><div><div class="tags"><span class="tag">${t.type==='long'?'Long term':'Short term'}</span><span class="tag ${t.payType==='revenue'?'revenue':''}">${t.payType==='revenue'?'Revenue':'USD'}</span>${t.completedAt?'<span class="tag done">Completed — deletes after 2 days</span>':''}</div><h2 class="item-title">${esc(t.title)}</h2><p class="item-description">${esc(t.description)}</p></div><div class="pay-box"><div class="pay-value">${p}</div><div class="pay-label">${t.payType==='revenue'?'expected revenue':'expected pay'}</div><div class="deadline ${dl[1]}">${dl[0]}</div></div></div>${t.checklist?.length?'<div class="checklist">'+t.checklist.map((c,i)=>`<label class="check-row ${c.done?'checked':''}"><input type="checkbox" data-check-task="${t.id}" data-i="${i}" ${c.done?'checked':''}><span>${esc(c.text)}</span></label>`).join('')+'</div>':''}<div class="card-actions">${!t.completedAt?`<button class="button small secondary" data-complete-task="${t.id}">✓ Complete task</button>`:''}<button class="button small secondary danger" data-delete-task="${t.id}">Delete</button></div></article>`}
function renderTasks(){const el=document.getElementById('task-list');if(!el)return;const d=data(),f=document.querySelector('#task-filter .active')?.dataset.filter||'all',s=document.getElementById('task-sort')?.value||'deadline-asc';let a=d.tasks.filter(x=>f==='all'||x.type===f);a.sort((x,y)=>{if(s.includes('deadline'))return(s==='deadline-asc'?1:-1)*(date(x.deadline)-date(y.deadline));if(s==='pay-desc'||s==='pay-asc')return(s==='pay-desc'?-1:1)*((parseFloat(y.pay)||-1)-(parseFloat(x.pay)||-1));if(s==='revenue'||s==='usd')return(s==='revenue'?'revenue':'usd')===x.payType?-1:1;if(s==='active')return!!x.completedAt-!!y.completedAt});el.innerHTML=a.map(taskCard).join('');document.getElementById('task-empty')?.classList.toggle('hidden',a.length>0)}
document.getElementById('task-filter')?.addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('#task-filter .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTasks()});document.getElementById('task-sort')?.addEventListener('change',renderTasks);
document.getElementById('task-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.tasks.push({id:id('task'),title:f.get('title'),description:f.get('description'),type:f.get('type'),payType:f.get('payType'),pay:f.get('pay'),deadline:f.get('deadline'),checklist:String(f.get('checklist')||'').split('\n').map(x=>x.trim()).filter(Boolean).map(text=>({text,done:false}))});save(d);e.target.reset();close();renderTasks()});
document.addEventListener('change',e=>{const x=e.target.closest('[data-check-task]');if(!x)return;const d=data(),t=d.tasks.find(a=>a.id===x.dataset.checkTask);if(!t)return;t.checklist[x.dataset.i].done=x.checked;if(t.checklist.length&&t.checklist.every(a=>a.done))t.completedAt=new Date().toISOString();save(d);renderTasks()});
document.addEventListener('click',e=>{let b=e.target.closest('[data-complete-task]');if(b){const d=data(),t=d.tasks.find(x=>x.id===b.dataset.completeTask);if(t)t.completedAt=new Date().toISOString();save(d);renderTasks()}b=e.target.closest('[data-delete-task]');if(b&&confirm('Delete this task permanently?')){const d=data();d.tasks=d.tasks.filter(x=>x.id!==b.dataset.deleteTask);save(d);renderTasks()}});

function nextPay(s){let n=date(s.startDate),t=date(iso());while(n<=t){if(s.frequency==='weekly')n.setDate(n.getDate()+7);else n.setMonth(n.getMonth()+1)}return iso(n)}
function renderSubs(){const l=document.getElementById('subscription-list');if(!l)return;const d=data();let a=d.subscriptions.map(x=>({...x,next:nextPay(x)}));const s=document.getElementById('subscription-sort')?.value||'next-asc';a.sort((x,y)=>s.startsWith('next')?(s==='next-asc'?1:-1)*(date(x.next)-date(y.next)):s==='cost-desc'?y.cost-x.cost:s==='cost-asc'?x.cost-y.cost:s==='weekly'?(y.frequency==='weekly')-(x.frequency==='weekly'):(y.frequency==='monthly')-(x.frequency==='monthly'));l.innerHTML=a.map(x=>`<article class="item-card"><div class="item-top"><div><div class="tags"><span class="tag">${x.frequency}</span><span class="tag">ZAR</span></div><h2 class="item-title">${esc(x.title)}</h2><p class="item-description">${esc(x.description)}</p><div class="subscription-meta">Started <strong>${fmtDate(x.startDate)}</strong></div></div><div class="pay-box"><div class="subscription-cost">${money(x.cost,'ZAR')}</div><div class="pay-label">${x.frequency}</div><div class="subscription-meta">Next <strong>${fmtDate(x.next)}</strong></div></div></div><div class="card-actions"><button class="button small secondary danger" data-delete-sub="${x.id}">Delete</button></div></article>`).join('');document.getElementById('subscription-empty')?.classList.toggle('hidden',a.length>0);const mo=d.subscriptions.filter(x=>x.frequency==='monthly').reduce((a,x)=>a+ +x.cost,0),w=d.subscriptions.filter(x=>x.frequency==='weekly').reduce((a,x)=>a+ +x.cost,0);document.getElementById('subscription-summary')&&(document.getElementById('subscription-summary').innerHTML=`<div class="summary"><div class="label">Subscriptions</div><div class="value">${d.subscriptions.length}</div><div class="sub">active recurring costs</div></div><div class="summary"><div class="label">Monthly direct</div><div class="value">${money(mo,'ZAR')}</div></div><div class="summary"><div class="label">Approx. monthly</div><div class="value">${money(mo+w*52/12,'ZAR')}</div><div class="sub">weekly costs converted</div></div>`)}
document.getElementById('subscription-sort')?.addEventListener('change',renderSubs);document.getElementById('subscription-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.subscriptions.push({id:id('sub'),title:f.get('title'),description:f.get('description'),cost:+f.get('cost'),frequency:f.get('frequency'),startDate:f.get('startDate')});save(d);e.target.reset();close();renderSubs()});document.addEventListener('click',e=>{const b=e.target.closest('[data-delete-sub]');if(b&&confirm('Delete this subscription?')){const d=data();d.subscriptions=d.subscriptions.filter(x=>x.id!==b.dataset.deleteSub);save(d);renderSubs()}});

function renderGoals(){const l=document.getElementById('goal-list');if(!l)return;const d=data(),f=document.querySelector('#goal-filter .active')?.dataset.filter||'all',s=document.getElementById('goal-sort')?.value||'type';let a=d.goals.filter(x=>f==='all'||x.type===f);a.sort((x,y)=>s==='cost-desc'?y.cost-x.cost:s==='cost-asc'?x.cost-y.cost:s==='currency'?(y.currency==='USD')-(x.currency==='USD'):s==='active'?!!x.completedAt-!!y.completedAt:s==='type-long'?(y.type==='long')-(x.type==='long'):(y.type==='short')-(x.type==='short'));l.innerHTML=a.map(g=>`<article class="item-card ${g.completedAt?'completed':''}"><div class="item-top"><div><div class="tags"><span class="tag">${g.type==='long'?'Long term':'Short term'}</span><span class="tag">${g.currency}</span>${g.completedAt?'<span class="tag done">Completed — deletes after 2 days</span>':''}</div><h2 class="item-title">${esc(g.title)}</h2><p class="item-description">${esc(g.description)}</p></div><div class="pay-box"><div class="goal-cost">${money(g.cost,g.currency)}</div><div class="pay-label">target cost</div></div></div><div class="card-actions">${!g.completedAt?`<button class="button small secondary" data-complete-goal="${g.id}">✓ Complete goal</button>`:''}<button class="button small secondary danger" data-delete-goal="${g.id}">Delete</button></div></article>`).join('');document.getElementById('goal-empty')?.classList.toggle('hidden',a.length>0)}
document.getElementById('goal-filter')?.addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('#goal-filter .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGoals()});document.getElementById('goal-sort')?.addEventListener('change',renderGoals);document.getElementById('goal-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.goals.push({id:id('goal'),title:f.get('title'),description:f.get('description'),type:f.get('type'),currency:f.get('currency'),cost:+f.get('cost')});save(d);e.target.reset();close();renderGoals()});document.addEventListener('click',e=>{let b=e.target.closest('[data-complete-goal]');if(b){const d=data(),g=d.goals.find(x=>x.id===b.dataset.completeGoal);g.completedAt=new Date().toISOString();save(d);renderGoals()}b=e.target.closest('[data-delete-goal]');if(b&&confirm('Delete this goal permanently?')){const d=data();d.goals=d.goals.filter(x=>x.id!==b.dataset.deleteGoal);save(d);renderGoals()}});

function periodMatch(v,p){const d=date(v),n=new Date();if(!d)return false;if(p==='day')return iso(d)===iso(n);if(p==='month')return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth();if(p==='year')return d.getFullYear()===n.getFullYear();return true}
function renderMoney(){const l=document.getElementById('money-list');if(!l)return;const d=data(),p=document.getElementById('analytics-period')?.value||'month';let a=d.money.filter(x=>periodMatch(x.date,p));const s=document.getElementById('money-sort')?.value||'new';a.sort((x,y)=>s==='new'?y.date.localeCompare(x.date):s==='old'?x.date.localeCompare(y.date):s==='high'?y.net-x.net:s==='low'?x.net-y.net:s==='usd'?(y.currency==='USD')-(x.currency==='USD'):(y.currency==='ROBUX')-(x.currency==='ROBUX'));l.innerHTML=a.map(x=>`<article class="item-card"><div class="item-top"><div><div class="tags"><span class="tag">${x.currency==='ROBUX'?'Robux':' '+x.currency}</span>${x.currency==='ROBUX'?'<span class="tag revenue">30% tax applied</span>':''}</div><h2 class="item-title">${money(x.net,x.currency)}</h2><p class="item-description">${esc(x.note||'Income transaction')}</p><div class="subscription-meta">${fmtDate(x.date)} ${x.currency==='ROBUX'?`• Entered ${Number(x.amount).toLocaleString()} → kept ${Number(x.net).toLocaleString()} Robux`:''}</div></div></div><div class="card-actions"><button class="button small secondary danger" data-delete-money="${x.id}">Delete</button></div></article>`).join('');document.getElementById('money-empty')?.classList.toggle('hidden',a.length>0);drawMoneyAnalytics(d,p);const thisMonth=d.money.filter(x=>periodMatch(x.date,'month'));const total=cur=>thisMonth.filter(x=>x.currency===cur).reduce((z,x)=>z+x.net,0);document.getElementById('money-summary').innerHTML=`<div class="summary"><div class="label">This month — ZAR</div><div class="value">${money(total('ZAR'),'ZAR')}</div></div><div class="summary"><div class="label">This month — USD</div><div class="value">${money(total('USD'),'USD')}</div></div><div class="summary"><div class="label">This month — Robux</div><div class="value">${money(total('ROBUX'),'ROBUX')}</div><div class="sub">after 30% tax</div></div>`}
function drawMoneyAnalytics(d,p){const arr=d.money.filter(x=>periodMatch(x.date,p));const groups={ZAR:0,USD:0,ROBUX:0};arr.forEach(x=>groups[x.currency]+=x.net);const total=Object.values(groups).reduce((a,b)=>a+b,0),don=document.getElementById('income-donut');if(don){let a=0,parts=[];for(const [k,v] of Object.entries(groups)){const pct=total?v/total*100:0;parts.push(`${k==='ZAR'?'#111827':k==='USD'?'#52606d':'#8b98a8'} ${a}% ${a+pct}%`);a+=pct}don.style.background=`conic-gradient(${parts.length?parts.join(','):'#dfe4ea 0 100%'})`;document.getElementById('donut-total').textContent=money(groups.ZAR,'ZAR');}document.getElementById('analytics-label').textContent=p==='day'?'Today':p==='month'?'This month':p==='year'?'This year':'All time';document.getElementById('income-legend').innerHTML=Object.entries(groups).map(([k,v])=>`<div class="legend-row"><div class="legend-left"><i class="dot"></i>${k}</div><strong>${money(v,k)}</strong></div>`).join('');const bars=document.getElementById('income-bars');if(!bars)return;let buckets=[];if(p==='day'){buckets=[{l:'Today',v:total}] }else if(p==='month'){const n=new Date().getDate();buckets=Array.from({length:n},(_,i)=>{const day=i+1;return{l:String(day),v:arr.filter(x=>date(x.date).getDate()===day).reduce((z,x)=>z+x.net,0)}})}else if(p==='year'){buckets=Array.from({length:12},(_,i)=>({l:new Date(2000,i,1).toLocaleString('en',{month:'short'}),v:arr.filter(x=>date(x.date).getMonth()===i).reduce((z,x)=>z+x.net,0)}))}else{buckets=Array.from({length:12},(_,i)=>({l:new Date(2000,i,1).toLocaleString('en',{month:'short'}),v:d.money.filter(x=>date(x.date).getMonth()===i).reduce((z,x)=>z+x.net,0)}))}const max=Math.max(1,...buckets.map(x=>x.v));bars.innerHTML=buckets.map(x=>`<div class="bar" title="${x.v}"><div class="bar-fill" style="height:${Math.max(2,x.v/max*100)}%"></div><span>${x.l}</span></div>`).join('')}
document.getElementById('analytics-period')?.addEventListener('change',renderMoney);document.getElementById('money-sort')?.addEventListener('change',renderMoney);document.getElementById('money-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),amount=+f.get('amount'),currency=f.get('currency'),d=data();d.money.push({id:id('money'),amount,net:currency==='ROBUX'?Math.floor(amount*.7):amount,currency,date:f.get('date'),note:f.get('note')});save(d);e.target.reset();close();renderMoney()});document.addEventListener('click',e=>{const b=e.target.closest('[data-delete-money]');if(b&&confirm('Delete this transaction?')){const d=data();d.money=d.money.filter(x=>x.id!==b.dataset.deleteMoney);save(d);renderMoney()}});

function renderRevenue(){const l=document.getElementById('revenue-list');if(!l)return;const d=data(),s=document.getElementById('revenue-sort')?.value||'payment';let a=[...d.revenue];a.sort((x,y)=>s==='high'?y.amount-x.amount:s==='low'?x.amount-y.amount:s==='name'?x.game.localeCompare(y.game):x.paymentDay-y.paymentDay);l.innerHTML=a.map(x=>`<article class="item-card"><div class="item-top"><div><div class="tags"><span class="tag">Monthly</span><span class="tag ${x.currency==='ROBUX'?'revenue':''}">${x.currency}</span></div><h2 class="item-title">${esc(x.game)}</h2><p class="item-description">${esc(x.description)}</p><div class="subscription-meta">Paid each month on <strong>the ${x.paymentDay}${['th','st','nd','rd'][(x.paymentDay%100-20)%10]||'th'}</strong></div></div><div class="pay-box"><div class="pay-value">${money(x.amount,x.currency)}</div><div class="pay-label">expected monthly</div></div></div><div class="card-actions"><button class="button small secondary danger" data-delete-revenue="${x.id}">Delete</button></div></article>`).join('');document.getElementById('revenue-empty')?.classList.toggle('hidden',a.length>0);drawRevenue(d)}
function drawRevenue(d){const groups={ZAR:0,USD:0,ROBUX:0};d.revenue.forEach(x=>groups[x.currency]+=x.amount);const total=Object.values(groups).reduce((a,b)=>a+b,0),don=document.getElementById('revenue-donut');if(don){let a=0,parts=[];for(const [k,v] of Object.entries(groups)){const pct=total?v/total*100:0;parts.push(`${k==='ZAR'?'#111827':k==='USD'?'#52606d':'#8b98a8'} ${a}% ${a+pct}%`);a+=pct}don.style.background=`conic-gradient(${parts.length?parts.join(','):'#dfe4ea 0 100%'})`}document.getElementById('revenue-total').textContent=money(groups.ZAR,'ZAR');document.getElementById('revenue-legend').innerHTML=Object.entries(groups).map(([k,v])=>`<div class="legend-row"><div class="legend-left"><i class="dot"></i>${k}</div><strong>${money(v,k)}</strong></div>`).join('');document.getElementById('revenue-summary').innerHTML=`<div class="summary"><div class="label">Revenue streams</div><div class="value">${d.revenue.length}</div></div><div class="summary"><div class="label">ZAR monthly</div><div class="value">${money(groups.ZAR,'ZAR')}</div></div><div class="summary"><div class="label">USD monthly</div><div class="value">${money(groups.USD,'USD')}</div></div>`}
document.getElementById('revenue-sort')?.addEventListener('change',renderRevenue);document.getElementById('revenue-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.revenue.push({id:id('rev'),game:f.get('game'),amount:+f.get('amount'),currency:f.get('currency'),paymentDay:+f.get('paymentDay'),description:f.get('description')});save(d);e.target.reset();close();renderRevenue()});document.getElementById('revenue-period')?.addEventListener('change',()=>drawRevenue(data()));document.addEventListener('click',e=>{const b=e.target.closest('[data-delete-revenue]');if(b&&confirm('Delete this revenue stream?')){const d=data();d.revenue=d.revenue.filter(x=>x.id!==b.dataset.deleteRevenue);save(d);renderRevenue()}});

function backup(){const blob=new Blob([JSON.stringify(data(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='freelance-tracker-backup-'+iso()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}document.getElementById('export-data')?.addEventListener('click',backup);document.getElementById('import-data')?.addEventListener('change',e=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.tasks||!x.goals||!x.subscriptions)throw 0;save({...seed,...x});location.reload()}catch{alert('Invalid backup file.')}};r.readAsText(e.target.files[0])});

document.querySelectorAll('input[type=date]').forEach(x=>{if(!x.value)x.value=iso()});data();renderTasks();renderSubs();renderGoals();renderMoney();renderRevenue();
