const KEY="freelance_tracker_v1";
const empty={tasks:[],subscriptions:[],goals:[]};
const $=s=>document.querySelector(s);
function data(){let d;try{d=JSON.parse(localStorage.getItem(KEY)||"null")}catch{d=null}d=d&&typeof d==="object"?d:structuredClone(empty);d.tasks??=[];d.subscriptions??=[];d.goals??=[];cleanup(d);save(d);return d}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function today(){let d=new Date();d.setHours(0,0,0,0);return d}function parse(v){if(!v)return null;let [y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d)}
function iso(d=today()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function days(v){let d=parse(v);return Math.round((d-today())/86400000)}
function deadline(v){let n=days(v);if(n<0)return `<span class="deadline overdue">${-n} day${-n===1?"":"s"} overdue</span>`;if(n===0)return `<span class="deadline today">Today</span>`;return `<span class="deadline">${n} day${n===1?"":"s"} left</span>`}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function money(n,c){return c==="ZAR"?`R${Number(n).toLocaleString("en-ZA",{minimumFractionDigits:2,maximumFractionDigits:2})}`:`$${Number(n).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function pay(v){if(String(v).trim()==="?")return {unknown:true,n:-Infinity};let n=Number(String(v).replace(/[^0-9.-]/g,""));return {unknown:!Number.isFinite(n),n:Number.isFinite(n)?n:-Infinity}}
function cleanup(d){let cut=Date.now()-172800000;for(const k of ["tasks","goals"])d[k]=d[k].filter(x=>!x.completedAt||Date.parse(x.completedAt)>cut)}
function modalEvents(){document.addEventListener("click",e=>{let o=e.target.closest("[data-open]");if(o)$("#"+o.dataset.open)?.classList.remove("hidden");if(e.target.closest("[data-close]")||e.target.classList.contains("modal"))e.target.closest(".modal")?.classList.add("hidden")})}
function taskRender(){let l=$("#task-list");if(!l)return;let d=data(),f=$("#task-filter .active")?.dataset.filter||"all",s=$("#task-sort")?.value||"deadline-asc",a=d.tasks.filter(x=>f==="all"||x.type===f);a.sort((x,y)=>{if(s.includes("deadline"))return (s==="deadline-asc"?1:-1)*(parse(x.deadline)-parse(y.deadline));if(s.includes("pay")){let p=pay(x.pay).n,q=pay(y.pay).n;return s==="pay-desc"?q-p:p-q}if(s==="revenue"||s==="usd")return (y.payType===s)-(x.payType===s);return 0});l.innerHTML=a.map(t=>`<article class="card ${t.completedAt?"completed":""}"><div class="top"><div><div class="tags"><span class="tag">${t.type} term</span><span class="tag ${t.payType==='revenue'?'revenue':''}">${t.payType==='revenue'?'Revenue':'USD'}</span>${t.completedAt?'<span class="tag">Completed — deletes after 2 days</span>':''}</div><h2 class="title">${esc(t.title)}</h2><p class="desc">${esc(t.description)}</p></div><div class="pay">${pay(t.pay).unknown?'UNKNOWN':esc(t.pay)}<small>${t.payType==='revenue'?'revenue':'expected pay'}</small>${deadline(t.deadline)}</div></div>${t.checklist?.length?`<div class="checklist">${t.checklist.map((c,i)=>`<label class="check ${c.done?'done':''}"><input type="checkbox" data-check="${t.id}" data-i="${i}" ${c.done?'checked':''}>${esc(c.text)}</label>`).join("")}</div>`:""}<div class="card-actions">${!t.completedAt?`<button class="btn" data-complete="${t.id}">✓ Complete</button>`:""}<button class="btn danger" data-delete="${t.id}">Delete</button></div></article>`).join("");$("#task-empty")?.classList.toggle("hidden",a.length>0)}
function subNext(start,freq){let n=parse(start),t=today();while(n<=t)freq==="weekly"?n.setDate(n.getDate()+7):n.setMonth(n.getMonth()+1);return n}
function subRender(){let l=$("#sub-list");if(!l)return;let d=data(),s=$("#sub-sort")?.value||"next",a=d.subscriptions.map(x=>({...x,next:subNext(x.startDate,x.frequency)}));a.sort((x,y)=>s==="next"?x.next-y.next:s==="cost-desc"?y.cost-x.cost:s==="cost-asc"?x.cost-y.cost:s==="weekly"?(y.frequency==="weekly")-(x.frequency==="weekly"):(y.frequency==="monthly")-(x.frequency==="monthly"));l.innerHTML=a.map(x=>`<article class="card"><div class="top"><div><div class="tags"><span class="tag">${x.frequency}</span><span class="tag">ZAR</span></div><h2 class="title">${esc(x.title)}</h2><p class="desc">${esc(x.description)}</p><div class="muted">Next payment: <b>${x.next.toLocaleDateString("en-ZA",{day:"numeric",month:"short",year:"numeric"})}</b></div></div><div class="pay">${money(x.cost,"ZAR")}<small>${x.frequency}</small></div></div><div class="card-actions"><button class="btn danger" data-sub-delete="${x.id}">Delete</button></div></article>`).join("");$("#sub-empty")?.classList.toggle("hidden",a.length>0);let monthly=d.subscriptions.filter(x=>x.frequency==="monthly").reduce((n,x)=>n+Number(x.cost),0),weekly=d.subscriptions.filter(x=>x.frequency==="weekly").reduce((n,x)=>n+Number(x.cost),0),m=monthly+weekly*52/12;$("#sub-summary").innerHTML=`<div class="card"><span>Subscriptions</span><b>${d.subscriptions.length}</b></div><div class="card"><span>Monthly direct</span><b>${money(monthly,"ZAR")}</b></div><div class="card"><span>Approx. monthly</span><b>${money(m,"ZAR")}</b></div>`}
function goalRender(){let l=$("#goal-list");if(!l)return;let d=data(),f=$("#goal-filter .active")?.dataset.filter||"all",s=$("#goal-sort")?.value||"short",a=d.goals.filter(x=>f==="all"||x.type===f);a.sort((x,y)=>s==="short"?(y.type==="short")-(x.type==="short"):s==="long"?(y.type==="long")-(x.type==="long"):s==="cost-desc"?y.cost-x.cost:s==="cost-asc"?x.cost-y.cost:(y.currency==="USD")-(x.currency==="USD"));l.innerHTML=a.map(g=>`<article class="card ${g.completedAt?'completed':''}"><div class="top"><div><div class="tags"><span class="tag">${g.type} term</span><span class="tag">${g.currency}</span>${g.completedAt?'<span class="tag">Completed — deletes after 2 days</span>':''}</div><h2 class="title">${esc(g.title)}</h2><p class="desc">${esc(g.description)}</p></div><div class="pay">${money(g.cost,g.currency)}<small>target cost</small></div></div><div class="card-actions">${!g.completedAt?`<button class="btn" data-goal-complete="${g.id}">✓ Complete</button>`:""}<button class="btn danger" data-goal-delete="${g.id}">Delete</button></div></article>`).join("");$("#goal-empty")?.classList.toggle("hidden",a.length>0)}
function formSetup(){let tf=$("#task-form");tf?.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(tf),d=data();d.tasks.push({id:id(),title:f.get("title").trim(),description:f.get("description").trim(),type:f.get("type"),payType:f.get("payType"),pay:f.get("pay").trim(),deadline:f.get("deadline"),checklist:String(f.get("checklist")).split("\n").map(x=>x.trim()).filter(Boolean).map(text=>({text,done:false}))});save(d);tf.closest(".modal").classList.add("hidden");tf.reset();taskRender()});let sf=$("#sub-form");sf?.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(sf),d=data();d.subscriptions.push({id:id(),title:f.get("title").trim(),description:f.get("description").trim(),cost:Number(f.get("cost")),frequency:f.get("frequency"),startDate:f.get("startDate")});save(d);sf.closest(".modal").classList.add("hidden");sf.reset();subRender()});let gf=$("#goal-form");gf?.addEventListener("submit",e=>{e.preventDefault();let f=new FormData(gf),d=data();d.goals.push({id:id(),title:f.get("title").trim(),description:f.get("description").trim(),type:f.get("type"),currency:f.get("currency"),cost:Number(f.get("cost"))});save(d);gf.closest(".modal").classList.add("hidden");gf.reset();goalRender()})}
function controls(){document.addEventListener("click",e=>{let b=e.target.closest(".tabs button");if(b){b.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");taskRender();goalRender()}let c=e.target.closest("[data-complete]");if(c){let d=data(),x=d.tasks.find(x=>x.id===c.dataset.complete);if(x){x.completedAt=new Date().toISOString();save(d);taskRender()}}let del=e.target.closest("[data-delete]");if(del){if(confirm("Delete this task permanently?")){let d=data();d.tasks=d.tasks.filter(x=>x.id!==del.dataset.delete);save(d);taskRender()}}let sd=e.target.closest("[data-sub-delete]");if(sd){if(confirm("Delete this subscription?")){let d=data();d.subscriptions=d.subscriptions.filter(x=>x.id!==sd.dataset.subDelete);save(d);subRender()}}let gc=e.target.closest("[data-goal-complete]");if(gc){let d=data(),x=d.goals.find(x=>x.id===gc.dataset.goalComplete);if(x){x.completedAt=new Date().toISOString();save(d);goalRender()}}let gd=e.target.closest("[data-goal-delete]");if(gd){if(confirm("Delete this goal permanently?")){let d=data();d.goals=d.goals.filter(x=>x.id!==gd.dataset.goalDelete);save(d);goalRender()}}});document.addEventListener("change",e=>{let c=e.target.closest("[data-check]");if(!c)return;let d=data(),t=d.tasks.find(x=>x.id===c.dataset.check);if(t){t.checklist[c.dataset.i].done=c.checked;if(t.checklist.length&&t.checklist.every(x=>x.done))t.completedAt=new Date().toISOString();save(d);taskRender()}});$("#task-sort")?.addEventListener("change",taskRender);$("#sub-sort")?.addEventListener("change",subRender);$("#goal-sort")?.addEventListener("change",goalRender);$("#export")?.addEventListener("click",()=>{let blob=new Blob([JSON.stringify(data(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`freelance-tracker-backup-${iso()}.json`;a.click();URL.revokeObjectURL(a.href)});$("#import")?.addEventListener("change",e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.tasks)||!Array.isArray(x.subscriptions)||!Array.isArray(x.goals))throw 0;save(x);location.reload()}catch{alert("Invalid Freelance Tracker backup.")}};r.readAsText(f)})}
function init(){data();modalEvents();formSetup();controls();[...document.querySelectorAll('input[type=date]')].forEach(x=>{if(x.name==="deadline"||x.name==="startDate")x.value=iso()});taskRender();subRender();goalRender()}init();
